### ISSUE TITLE
Read timed out when using session instance for a long time

### ISSUE THREAD

**Issue by Kostylev-av** [jawah/niquests#240]
Error Read timed out when using a session for a long time.

## Expected Result

No error, connection is being recreated

## Actual Result

Hi, I've run into an issue with how niquests POST requests to the server
We have:

- [x] One instance of the session: niquests.Session
- [x] Requests of the form session.post(url, data=data, verify=False, **kwargs) all requests are the same
- [x] Response analysis:

1. response is successful and response.conn_info.http_version.value = HTTP/2.0
2. response is successful and response.conn_info.http_version.value = HTTP/3.0
3. response is NOT successful and "HTTPSConnectionPool(host=<>, port=<>): Read timed out. (read timeout=<>)"
4. response is successful and response.conn_info.http_version.value = HTTP/2.0
5. response is successful and response.conn_info.http_version.value = HTTP/3.0
6. response is NOT successful and "HTTPSConnectionPool(host=<>, port=<>): Read timed out. (read timeout=<>)"

timeout can be anything, the url also doesn't change, only the data sent changes

It is important that there can be an interval between requests greater than keepalive_delay: float | int | None = 3600.0, it is after this time that the request error occurs with 100%

Is there a way to fix it?

## Reproduction Steps

```python
from niquests import Session
from niquests.adapters import HTTPAdapter


class ServiceDispatcher(object):

    def __init__(self):
        self.session = Session()
        self.session.trust_env = False
        self.session.mount("http://", HTTPAdapter(max_retries=3))
        self.session.mount("https://", HTTPAdapter(max_retries=3))

    def post(self):
        url = 'url'
        data = 'data'
        kwargs = {"headers": {}}
        return self.session.post(url, data=data, verify=False, timeout=20, **kwargs)


if __name__ == "__main__":
    sd = ServiceDispatcher()
    while True:
        try:
            response = sd.post()
            print(response.status_code)
            http_version = response.conn_info.http_version.value
            print("Http version: %s", http_version)
        except Exception as ex:
            print(ex)
            break

```

## System Information

    $ python -m niquests.help

```json
{
  "charset_normalizer": {
    "version": "3.4.1"
  },
  "gil": true,
  "http1": {
    "h11": "0.14.0"
  },
  "http2": {
    "jh2": "5.0.8"
  },
  "http3": {
    "enabled": true,
    "qh3": "1.4.3"
  },
  "idna": {
    "version": "3.10"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.10.11"
  },
  "niquests": {
    "version": "3.14.0"
  },
  "ocsp": {
    "enabled": true
  },
  "platform": {
    "release": "10",
    "system": "Windows"
  },
  "system_ssl": {
    "name": "OpenSSL 1.1.1t  7 Feb 2023",
    "version": "1010114f"
  },
  "urllib3.future": {
    "cohabitation_version": null,
    "version": "2.12.916"
  },
  "wassima": {
    "certifi_fallback": false,
    "enabled": true,
    "version": "1.2.2"
  },
  "websocket": {
    "enabled": false,
    "wsproto": null
  }
}

```

**Comment by Ousret** [comment]
this seems to be a bug on our side. I'll investigate and notify upon the resolution.
the connection should simply be dropped and reissued after the keepalive delay.

regards,

**Comment by Ousret** [comment]
It is fixed. We will publish a patch release for `urllib3-future`.
Install it when available with `pip install "urllib3-future==2.12.917"`.

Finally, you can drop the mount adapter thanks to the shortcut available in your Session constructor.

```python
class ServiceDispatcher(object):

    def __init__(self):
        self.session = Session()
        self.session.trust_env = False
        self.session.mount("http://", HTTPAdapter(max_retries=3))
        self.session.mount("https://", HTTPAdapter(max_retries=3))
```

becomes

```python
class ServiceDispatcher(object):

    def __init__(self):
        self.session = Session(retries=3)
        self.session.trust_env = False
```

**Comment by Kostylev-av** [comment]
Didn't help. Still getting a read timeout error when receiving the response

**Comment by Ousret** [comment]
OK. Something seems off.

In order to find the root cause, we'll ask you the following:

1) Copy and paste the full stack trace.
2) Enable advanced logging and paste it there.
3) Run the same with `disable_http3=True` within your session constructor.
4) provide the real URL, or if you cannot, the server software and version (e.g. nginx version x.y.z)


2* for advanced logging, add the following at top:

```python
import logging

logger = logging.getLogger()
logger.setLevel(logging.DEBUG)
explain_handler = logging.StreamHandler()
explain_handler.setFormatter(
    logging.Formatter("%(asctime)s | %(levelname)s | %(message)s")
)
logger.addHandler(explain_handler)
```

I'll leave the issue open until you can provide the requested informations.

regards,

**Comment by Kostylev-av** [comment]
### disable_http3=False
**stack trace**

> Connected to pydev debugger (build 211.7442.45)
2025-04-15 09:05:26,079 | DEBUG | Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
2025-04-15 09:05:26,079 | DEBUG | Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
2025-04-15 09:05:28,501 | DEBUG | Starting new HTTPS connection (1): w1239w11.comp.npo:444
2025-04-15 09:05:28,658 | DEBUG | https://w1239w11.comp.npo:444 "POST /Log/WriteEvents HTTP/2.0" 200 0
Response 200, Http version: HTTP/2.0
2025-04-15 09:05:42,095 | DEBUG | Resetting dropped connection: w1239w11.comp.npo
2025-04-15 09:05:42,204 | DEBUG | [6d4331e46f3fc768] TLS: Advertising to peer post-quantum algorithm using X25519ML768 (0x11EC)
2025-04-15 09:05:42,204 | DEBUG | [6d4331e46f3fc768] TLS State.CLIENT_HANDSHAKE_START -> State.CLIENT_EXPECT_SERVER_HELLO
2025-04-15 09:05:42,220 | DEBUG | [6d4331e46f3fc768] QuicConnectionState.FIRSTFLIGHT -> QuicConnectionState.CONNECTED
2025-04-15 09:05:42,235 | DEBUG | [6d4331e46f3fc768] Negotiated protocol version 0x00000001 (VERSION_1)
2025-04-15 09:05:42,235 | DEBUG | [6d4331e46f3fc768] TLS State.CLIENT_EXPECT_SERVER_HELLO -> State.CLIENT_EXPECT_ENCRYPTED_EXTENSIONS
2025-04-15 09:05:42,235 | DEBUG | [6d4331e46f3fc768] TLS State.CLIENT_EXPECT_ENCRYPTED_EXTENSIONS -> State.CLIENT_EXPECT_CERTIFICATE_REQUEST_OR_CERTIFICATE
2025-04-15 09:05:42,235 | DEBUG | [6d4331e46f3fc768] Discarding epoch Epoch.INITIAL
2025-04-15 09:05:42,235 | DEBUG | [6d4331e46f3fc768] TLS State.CLIENT_EXPECT_CERTIFICATE_REQUEST_OR_CERTIFICATE -> State.CLIENT_EXPECT_CERTIFICATE_VERIFY
2025-04-15 09:05:42,235 | DEBUG | [6d4331e46f3fc768] TLS State.CLIENT_EXPECT_CERTIFICATE_VERIFY -> State.CLIENT_EXPECT_FINISHED
2025-04-15 09:05:42,251 | DEBUG | [6d4331e46f3fc768] TLS State.CLIENT_EXPECT_FINISHED -> State.CLIENT_POST_HANDSHAKE
2025-04-15 09:05:42,251 | DEBUG | [6d4331e46f3fc768] ALPN negotiated protocol h3
2025-04-15 09:05:42,251 | DEBUG | [6d4331e46f3fc768] Stream 3 created by peer
2025-04-15 09:05:42,251 | DEBUG | [6d4331e46f3fc768] Stream 7 created by peer
2025-04-15 09:05:42,251 | DEBUG | [6d4331e46f3fc768] Stream 11 created by peer
2025-04-15 09:05:42,251 | DEBUG | [6d4331e46f3fc768] Discarding epoch Epoch.HANDSHAKE
2025-04-15 09:05:42,251 | DEBUG | https://w1239w11.comp.npo:444 "POST /Log/WriteEvents HTTP/3.0" 200 0
Response 200, Http version: HTTP/3.0
2025-04-15 09:06:31,627 | DEBUG | [6d4331e46f3fc768] Remote max_streams_bidi raised to 101
2025-04-15 09:06:31,627 | DEBUG | [6d4331e46f3fc768] Stream 0 discarded
2025-04-15 09:08:06,346 | DEBUG | [6d4331e46f3fc768] Sending PING in packet 13
2025-04-15 09:09:09,295 | DEBUG | [6d4331e46f3fc768] Sending PING in packet 14
2025-04-15 09:10:11,409 | DEBUG | [6d4331e46f3fc768] Sending PING in packet 15
2025-04-15 09:11:14,300 | DEBUG | [6d4331e46f3fc768] Sending PING in packet 16
2025-04-15 09:12:19,003 | DEBUG | [6d4331e46f3fc768] Sending PING in packet 17
2025-04-15 09:13:22,623 | DEBUG | [6d4331e46f3fc768] Sending PING in packet 18
2025-04-15 09:14:25,864 | DEBUG | [6d4331e46f3fc768] Sending PING in packet 19
2025-04-15 09:15:29,052 | DEBUG | [6d4331e46f3fc768] Sending PING in packet 20
2025-04-15 09:16:31,833 | DEBUG | [6d4331e46f3fc768] Sending PING in packet 21
2025-04-15 09:17:52,568 | DEBUG | [6d4331e46f3fc768] Connection close sent (code 0x0, reason )
2025-04-15 09:17:52,568 | DEBUG | [6d4331e46f3fc768] QuicConnectionState.CONNECTED -> QuicConnectionState.CLOSING
HTTPSConnectionPool(host='w1239w11.comp.npo', port=444): Read timed out. (read timeout=20)


### disable_http3=True, no errors
**stack trace**

>Connected to pydev debugger (build 211.7442.45)
2025-04-15 09:25:23,274 | DEBUG | Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
2025-04-15 09:25:23,289 | DEBUG | Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
2025-04-15 09:25:25,212 | DEBUG | Starting new HTTPS connection (1): w1239w11.comp.npo:444
2025-04-15 09:25:25,367 | DEBUG | https://w1239w11.comp.npo:444 "POST /Log/WriteEvents HTTP/2.0" 200 0
Response 200, Http version: HTTP/2.0
2025-04-15 09:25:29,227 | DEBUG | https://w1239w11.comp.npo:444 "POST /Log/WriteEvents HTTP/2.0" 200 0
Response 200, Http version: HTTP/2.0
2025-04-15 09:25:35,445 | DEBUG | https://w1239w11.comp.npo:444 "POST /Log/WriteEvents HTTP/2.0" 200 0
Response 200, Http version: HTTP/2.0
2025-04-15 09:31:38,088 | DEBUG | Resetting dropped connection: w1239w11.comp.npo
2025-04-15 09:31:38,198 | DEBUG | https://w1239w11.comp.npo:444 "POST /Log/WriteEvents HTTP/2.0" 200 0
Response 200, Http version: HTTP/2.0
2025-04-15 09:31:43,823 | DEBUG | https://w1239w11.comp.npo:444 "POST /Log/WriteEvents HTTP/2.0" 200 0
Response 200, Http version: HTTP/2.0
2025-04-15 09:31:50,370 | DEBUG | https://w1239w11.comp.npo:444 "POST /Log/WriteEvents HTTP/2.0" 200 0

**Comment by Kostylev-av** [comment]
server - IIS

**Comment by Ousret** [comment]
This time, it should be fixed.
Install it when available with `pip install "urllib3-future==2.12.918"`.

Regards,

**Comment by Kostylev-av** [comment]
The fix didn't work. The has_expired method fails when verifying 'self._quic._close_event is not None'. 
Providing the stack trace might help diagnose the problem.

Traceback (most recent call last):
  File "env\lib\site-packages\urllib3\connectionpool.py", line 1358, in _make_request
    response = conn.getresponse(
  File "env\lib\site-packages\urllib3\connection.py", line 625, in getresponse
    low_response = super().getresponse(
  File "env\lib\site-packages\urllib3\backend\hface.py", line 1473, in getresponse
    head_event: HeadersReceived | EarlyHeadersReceived = self.__exchange_until(  # type: ignore[assignment]
  File "env\lib\site-packages\urllib3\backend\hface.py", line 893, in __exchange_until
    data_in = self.sock.recv(self.blocksize)
TimeoutError: timed out

Traceback (most recent call last):
  File "env\lib\site-packages\urllib3\connectionpool.py", line 1791, in urlopen
    retries = retries.increment(
  File "env\lib\site-packages\urllib3\util\retry.py", line 499, in increment
    raise reraise(type(error), error, _stacktrace)
  File "env\lib\site-packages\urllib3\util\util.py", line 39, in reraise
    raise value
  File "env\lib\site-packages\urllib3\connectionpool.py", line 1713, in urlopen
    response = self._make_request(  # type: ignore[call-overload,misc]
  File "env\lib\site-packages\urllib3\connectionpool.py", line 1362, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "env\lib\site-packages\urllib3\connectionpool.py", line 815, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='w1152w10', port=443): Read timed out. (read timeout=20)

**Comment by Ousret** [comment]
we attempted yet another fix.
if that one does not help, we'll be completely out of clues. your server seems to be reluctant to keep the connection alive and ignore Ping frames.

upgrade using `pip install "urllib3-future==2.12.919"` when available. report back afterward.

**Comment by Kostylev-av** [comment]
Super! Now there are no errors, but we're experiencing a full timeout delay here: data_in = self.sock.recv(self.blocksize)
After waiting 15-20 seconds, a ConnectionTerminated error with code WAIT_TIMEOUT (258) appears in the self._protocol.events, which triggers a ReadTimeout error. If handled by closing the connection, it re-establishes successfully, but the read timeout delay persists and causes interference
works if you don't assign 
return self.session.post(url, data=data, timeout=timeout, verify=False, **kwargs)

**Comment by Ousret** [comment]
This should be the last piece of it. we disabled the session ticket that trigger 0-RTT handshake by default with QUIC. I highly suspect your server is rejecting his own ticket.

`pip install "urllib3-future==2.12.920"`.

If anything is still off, give us the logs as you did in https://github.com/jawah/niquests/issues/240#issuecomment-2803865529

regards,
