### ISSUE TITLE
difficulties with sharing a multiplexed connection amongst multiple threads

### ISSUE THREAD

**Issue by bakaiadam** [jawah/niquests#65]
print the headers, overcome the issues instead of stack trace errors.

It looks like it only happens if
```
rsession= niquests.Session(resolver="doh+google://", multiplexed=True)
```
Only timeout error happens when using this: 
```
rsession= niquests.Session()
```

## Actual Result

various stack traces. They happen randomly:

```
    ret=rsession.get(url, headers=headers,timeout=111)
  File "/home/adam/.local/lib/python3.10/site-packages/niquests/sessions.py", line 556, in get
    return self.request(
  File "/home/adam/.local/lib/python3.10/site-packages/niquests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/adam/.local/lib/python3.10/site-packages/niquests/sessions.py", line 1183, in send
    for resp_or_req in gen:
  File "/home/adam/.local/lib/python3.10/site-packages/niquests/sessions.py", line 1548, in resolve_redirects
    extract_cookies_to_jar(self.cookies, prepared_request, resp.raw)
  File "/home/adam/.local/lib/python3.10/site-packages/niquests/cookies.py", line 148, in extract_cookies_to_jar
    raise ValueError(
ValueError: Attempt to extract cookie from undefined request and/or response


 File "/home/adam/bmplayer/youtube_webserver.py", line 1292, in get_response3
    debug_print("do connection end",url,headers,"\nret headers:",ret.headers )
  File "/home/adam/.local/lib/python3.10/site-packages/niquests/models.py", line 994, in __getattribute__
    self._gather()
  File "/home/adam/.local/lib/python3.10/site-packages/niquests/sessions.py", line 1136, in <lambda>
    r._gather = lambda: adapter.gather(r)
  File "/home/adam/.local/lib/python3.10/site-packages/niquests/adapters.py", line 1058, in gather
    self.gather()
  File "/home/adam/.local/lib/python3.10/site-packages/niquests/adapters.py", line 1023, in gather
    self._future_handler(response, low_resp)
  File "/home/adam/.local/lib/python3.10/site-packages/niquests/adapters.py", line 983, in _future_handler
    response.content
  File "/home/adam/.local/lib/python3.10/site-packages/niquests/models.py", line 995, in __getattribute__
    return super().__getattribute__(item)
  File "/home/adam/.local/lib/python3.10/site-packages/niquests/models.py", line 1275, in content
    raise ChunkedEncodingError(e)
niquests.exceptions.ChunkedEncodingError: 25:No recent network activity after 63000545us. Timeout:63s


  File "/home/adam/bmplayer/youtube_webserver.py", line 1292, in get_response3
    debug_print("do connection end",url,headers,"\nret headers:",ret.headers )
  File "/home/adam/.local/lib/python3.10/site-packages/niquests/models.py", line 994, in __getattribute__
    self._gather()
  File "/home/adam/.local/lib/python3.10/site-packages/niquests/sessions.py", line 1136, in <lambda>
    r._gather = lambda: adapter.gather(r)
  File "/home/adam/.local/lib/python3.10/site-packages/niquests/adapters.py", line 1052, in gather
    self._future_handler(response, low_resp)
  File "/home/adam/.local/lib/python3.10/site-packages/niquests/adapters.py", line 921, in _future_handler
    next_promise._promise.set_parameter(k, v)
  File "/home/adam/.local/lib/python3.10/site-packages/niquests/models.py", line 995, in __getattribute__
    return super().__getattribute__(item)
AttributeError: 'Response' object has no attribute '_promise'
```

## Reproduction Steps
I can't reproduce with outside http servers, but something like this:

```python
import niquests

rsession= niquests.Session(resolver="doh+google://", multiplexed=True)

while True:
#  ret=rsession.get("http://192.168.100.1",timeout=111)
  ret=rsession.get("https://youtube.com",timeout=111)                       
  print("do connection end headers:",ret.headers )
```

## System Information

    $ python -m niquests.help

```json
{
{
  "charset_normalizer": {
    "version": "3.2.0"
  },
  "cryptography": {
    "version": "38.0.4"
  },
  "http1": {
    "h11": "0.14.0"
  },
  "http2": {
    "h2": "4.1.0"
  },
  "http3": {
    "enabled": true,
    "qh3": "0.14.0"
  },
  "idna": {
    "version": "3.3"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.10.12"
  },
  "niquests": {
    "version": "3.4.2"
  },
  "ocsp": {
    "enabled": true
  },
  "platform": {
    "release": "5.15.0-91-lowlatency",
    "system": "Linux"
  },
  "system_ssl": {
    "version": "30000020"
  },
  "urllib3.future": {
    "version": "2.4.903"
  },
  "wassima": {
    "certifi_fallback": false,
    "enabled": true,
    "version": "1.0.3"
  }
}

}
```

**Comment by Ousret** [comment]
From what I am seeing in there you are in a "threaded" environment (web server) and somewhat it breaks some internal algorithms.
Unfortunately, with what is at my disposal, I cannot reproduce. 

Could you share the program so that I have a better chance at fixing this issue? If not, I could take longer to find the root cause.

Regards,

**Comment by bakaiadam** [comment]
Sorry, I'm not going to share the original code, but here is a threaded version, it generates error:
```
import niquests

rsession= niquests.Session(resolver="doh+google://", multiplexed=True)

#rsession= niquests.Session(resolver="doh+google://", multiplexed=False)

from threading import Thread
from time import sleep

def threaded_function():
  while True:
#  ret=rsession.get("http://192.168.100.1",timeout=111)
    ret=rsession.get("https://youtube.com",timeout=111)                       
    print("do connection end headers:",ret.headers )

for i in range(0,2):    
  thread = Thread(target = threaded_function)
  thread.start()
```
 this is the error:
 ```
[92f674ef48988d42] Error: 298, reason: unable to get local issuer certificate, frame_type: 6
Exception in thread Thread-2 (threaded_function):
Traceback (most recent call last):
Exception in thread Thread-1 (threaded_function):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self.run()
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/threading.py", line 953, in run
  File "/home/adam/bmplayer/test3.py", line 14, in threaded_function
    self._target(*self._args, **self._kwargs)
  File "/home/adam/bmplayer/test3.py", line 14, in threaded_function
    print("do connection end headers:",ret.headers )
  File "/home/adam/.local/lib/python3.10/site-packages/niquests/models.py", line 994, in __getattribute__
    print("do connection end headers:",ret.headers )
  File "/home/adam/.local/lib/python3.10/site-packages/niquests/models.py", line 994, in __getattribute__
    self._gather()
  File "/home/adam/.local/lib/python3.10/site-packages/niquests/sessions.py", line 1136, in <lambda>
    r._gather = lambda: adapter.gather(r)
  File "/home/adam/.local/lib/python3.10/site-packages/niquests/adapters.py", line 1045, in gather
    self._gather()
    raise MultiplexingError(
  File "/home/adam/.local/lib/python3.10/site-packages/niquests/sessions.py", line 1136, in <lambda>
niquests.exceptions.MultiplexingError: Underlying library did not recognize our promise when asked to retrieve it. Did you close the session too early?
    r._gather = lambda: adapter.gather(r)
  File "/home/adam/.local/lib/python3.10/site-packages/niquests/adapters.py", line 1058, in gather
    self.gather()
  File "/home/adam/.local/lib/python3.10/site-packages/niquests/adapters.py", line 1019, in gather
    raise MultiplexingError(
niquests.exceptions.MultiplexingError: Underlying library yield an unexpected response that did not match any of sent request by us
```

I think the timeout issue is not related to the multithreading. Is there any solution to not throw "No recent network activity after 630005" error, but just reconnect after long inactivity?

**Comment by Ousret** [comment]
> but here is a threaded version, it generates error

OK, I am going to investigate and see what can be done in that exact context asap.

> Is there any solution to not throw 

Yes, set the `retries` parameter in `Session`. We will improve this situation soon.

**Comment by Ousret** [comment]
Update on the case.

We fixed 2 out of 3 things required for this.

- `No recent network activity after ..` is fixed in urllib3.future
- multiplexing and redirects could induces "leaking" lazy responses when accessed directly
- multiplexing and threads with a fairly fast pace could raise a MultiplexedError due to a connectionpool lock (unavailability for thread safety reasons)

only the last point remain. 

run `pip install niquests -U` to fetch latest fixes.
in the meantime, you can do the following "hack" to circumvent the last issue (conn unavailability for thread safety reasons)

```python
import niquests

from threading import Thread
from time import sleep

rsession = niquests.Session(resolver="doh+google://", multiplexed=True)

def threaded_function():
    while True:
        ret = rsession.get("https://pie.dev/redirect/3")
        while True:
            try:
                print(ret.headers)
                break
            except niquests.exceptions.MultiplexingError:
                pass


if __name__ == "__main__":

    for i in range(2):
        thread = Thread(target=threaded_function)
        thread.start()

    sleep(10)
```

As an aside note, you should know that multiplexing is only useful when emitting multiple requests before accessing them.

**Comment by Ousret** [comment]
Re:

It took a fair amount of time, but it was a complex subject.
We fixed it. Upgrade Niquests and urllib3-future to the latest versions.
Let us know if anything is wrong.

Regards,

**Comment by bakaiadam** [comment]
Thanks. This error still happens:
`    if ret.status_code==404:
  File "/home/adam/.local/lib/python3.10/site-packages/niquests/models.py", line 991, in __getattribute__
    self._gather()
  File "/home/adam/.local/lib/python3.10/site-packages/niquests/models.py", line 981, in _gather
    self.connection.gather(self)
  File "/home/adam/.local/lib/python3.10/site-packages/niquests/adapters.py", line 1061, in gather
    next_resp = self._future_handler(response, low_resp)
  File "/home/adam/.local/lib/python3.10/site-packages/niquests/adapters.py", line 927, in _future_handler
    next_promise._promise.set_parameter(k, v)
  File "/home/adam/.local/lib/python3.10/site-packages/niquests/models.py", line 992, in __getattribute__
    return super().__getattribute__(item)
AttributeError: 'Response' object has no attribute '_promise'`

Most of the time the session.get command returns a response, but sometimes it returns a ResponsePromise. When it returns a responsepromise then it won't work.

an other thing I found:
`  File "/home/adam/bmplayer/youtube_webserver.py", line 261, in rsession_get
    return n.get(*args,**kwargs)
  File "/home/adam/.local/lib/python3.10/site-packages/niquests/sessions.py", line 585, in get
    return self.request(
  File "/home/adam/.local/lib/python3.10/site-packages/niquests/sessions.py", line 531, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/adam/.local/lib/python3.10/site-packages/niquests/sessions.py", line 1162, in send
    r = adapter.send(request, **kwargs)
  File "/home/adam/.local/lib/python3.10/site-packages/niquests/adapters.py", line 698, in send
    conn = self.get_connection(request.url, proxies)
  File "/home/adam/.local/lib/python3.10/site-packages/niquests/adapters.py", line 570, in get_connection
    conn = self.poolmanager.connection_from_url(url)
  File "/home/adam/.local/lib/python3.10/site-packages/urllib3_future/poolmanager.py", line 474, in connection_from_url
    return self.connection_from_host(
  File "/home/adam/.local/lib/python3.10/site-packages/urllib3_future/poolmanager.py", line 406, in connection_from_host
    return self.connection_from_context(request_context)
  File "/home/adam/.local/lib/python3.10/site-packages/urllib3_future/poolmanager.py", line 429, in connection_from_context
    return self.connection_from_pool_key(pool_key, request_context=request_context)
  File "/home/adam/.local/lib/python3.10/site-packages/urllib3_future/poolmanager.py", line 446, in connection_from_pool_key
    pool = self.pools.locate(pool_key, block=False)
  File "/home/adam/.local/lib/python3.10/site-packages/urllib3_future/util/traffic_police.py", line 453, in locate
    raise UnavailableTraffic("Unavailable connection")
urllib3_future.util.traffic_police.UnavailableTraffic: Unavailable connection


`
 I get this error sometimes. I tried to change adapters.py to use urllib3_future poolmanager, but I get the same error with changing the line "if HAS_LEGACY_URLLIB3 is True:" or false.

**Comment by Ousret** [comment]
Re:

1) I suspect you have a redirection from a multiplexed capable endpoint to a non capable one (presumably https to http).
I'll need to put in place a reproducer.
2) OK, will look into it asap.

**Comment by Ousret** [comment]
With latests, do you still encounter issues?

**Comment by bakaiadam** [comment]
Thanks for the patches. I don't get the previous errors, but I got different ones, which I don't know if relevant:

```
 File "/home/adam/.local/lib/python3.10/site-packages/niquests/sessions.py", line 585, in get
    return self.request(
  File "/home/adam/.local/lib/python3.10/site-packages/niquests/sessions.py", line 531, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/adam/.local/lib/python3.10/site-packages/niquests/sessions.py", line 1162, in send
    r = adapter.send(request, **kwargs)
  File "/home/adam/.local/lib/python3.10/site-packages/niquests/adapters.py", line 783, in send
    conn = self.get_connection(request.url, proxies)
  File "/home/adam/.local/lib/python3.10/site-packages/niquests/adapters.py", line 660, in get_connection
    conn = self.poolmanager.connection_from_url(url)
  File "/home/adam/.local/lib/python3.10/site-packages/urllib3/poolmanager.py", line 474, in connection_from_url
    return self.connection_from_host(
  File "/home/adam/.local/lib/python3.10/site-packages/urllib3/poolmanager.py", line 406, in connection_from_host
    return self.connection_from_context(request_context)
  File "/home/adam/.local/lib/python3.10/site-packages/urllib3/poolmanager.py", line 429, in connection_from_context
    return self.connection_from_pool_key(pool_key, request_context=request_context)
  File "/home/adam/.local/lib/python3.10/site-packages/urllib3/poolmanager.py", line 456, in connection_from_pool_key
    self.pools.put(pool, pool_key, immediately_unavailable=True)
  File "/home/adam/.local/lib/python3.10/site-packages/urllib3/util/traffic_police.py", line 225, in put
    self._sacrifice_first_idle()
  File "/home/adam/.local/lib/python3.10/site-packages/urllib3/util/traffic_police.py", line 200, in _sacrifice_first_idle
    raise OverwhelmedTraffic(
urllib3.util.traffic_police.OverwhelmedTraffic: Cannot select a disposable connection to ease the charge
```
I tried to reproduce it but I couldn't do it.  


The other one is obviously known already:
```
   debug_print(ret,ret.status_code)
  File "/home/adam/.local/lib/python3.10/site-packages/niquests/models.py", line 1014, in __getattribute__
    self._gather()
  File "/home/adam/.local/lib/python3.10/site-packages/niquests/models.py", line 1003, in _gather
    self.connection.gather(self)
  File "/home/adam/.local/lib/python3.10/site-packages/niquests/adapters.py", line 1163, in gather
    next_resp = self._future_handler(response, low_resp)
  File "/home/adam/.local/lib/python3.10/site-packages/niquests/adapters.py", line 995, in _future_handler
    raise MultiplexingError(
niquests.exceptions.MultiplexingError: A multiplexed request led to a non-multiplexed response after a redirect. This is currently unsupported. A patch is in the making to support that edge case.

```

**Comment by bakaiadam** [comment]
I noticed I get this error:
```
  File "/home/adam/.local/lib/python3.10/site-packages/niquests/sessions.py", line 585, in get
    return self.request(
  File "/home/adam/.local/lib/python3.10/site-packages/niquests/sessions.py", line 531, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/adam/.local/lib/python3.10/site-packages/niquests/sessions.py", line 1215, in send
    for resp_or_req in gen:
  File "/home/adam/.local/lib/python3.10/site-packages/niquests/sessions.py", line 1588, in resolve_redirects
    resp.status_code
  File "/home/adam/.local/lib/python3.10/site-packages/niquests/models.py", line 1014, in __getattribute__
    self._gather()
  File "/home/adam/.local/lib/python3.10/site-packages/niquests/models.py", line 1003, in _gather
    self.connection.gather(self)
  File "/home/adam/.local/lib/python3.10/site-packages/niquests/adapters.py", line 1148, in gather
    low_resp = self.poolmanager.get_response(
  File "/home/adam/.local/lib/python3.10/site-packages/urllib3/poolmanager.py", line 525, in get_response
    response = pool.get_response(promise=promise)
  File "/home/adam/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 488, in get_response
    response = conn.getresponse(promise=promise, police_officer=self.pool)
  File "/home/adam/.local/lib/python3.10/site-packages/urllib3/connection.py", line 546, in getresponse
    low_response = super().getresponse(promise=promise)
  File "/home/adam/.local/lib/python3.10/site-packages/urllib3/backend/hface.py", line 927, in getresponse
    events: list[HeadersReceived] = self.__exchange_until(  # type: ignore[assignment]
  File "/home/adam/.local/lib/python3.10/site-packages/urllib3/backend/hface.py", line 680, in __exchange_until
    raise ProtocolError(event.message)
urllib3.exceptions.ProtocolError: 25:No recent network activity after 123010172us. Timeout:123s
```

this how session is created:
```
    rsession2= r.Session(resolver="doh+google://", multiplexed=True,retries=99)       
    adapter2 = r.adapters.HTTPAdapter(max_retries=99)
    rsession2.mount('https://', adapter2)
    rsession2.mount('http://', adapter2)
```
it works fine if it is not multiplexed

**Comment by Ousret** [comment]
> urllib3.util.traffic_police.OverwhelmedTraffic: Cannot select a disposable connection to ease the charge

for this, you need to increase pool_maxsize to at least the number of threads you are handling.

```python
rsession2= r.Session(resolver="doh+google://", multiplexed=True,retries=99)       
adapter2 = r.adapters.HTTPAdapter(max_retries=99)
rsession2.mount('https://', adapter2)
rsession2.mount('http://', adapter2)
```

should rather just be, other lines are duplicate and actually are missing some parameters.

```python
rsession2= r.Session(resolver="doh+google://", multiplexed=True, retries=99) 
```

Finally,

> 25:No recent network activity after 123010172us. Timeout:123s

I will look into it.
